defaults:
  - config

data:
  data_path: "/gcs/ml_ops_102_bucket/data/processed"

paths:
  output_dir: "/gcs/ml_ops_102_bucket/outputs"
  models_dir: "${paths.output_dir}/models"
  checkpoints_dir: "${paths.output_dir}/checkpoints"
  log_dir: "${paths.output_dir}/logs"

hydra:
  run:
    dir: .
  job:
    chdir: false

wandb:
  enabled: false

api:
  logging_location: "/gcs/ml_ops_102_bucket/logs"
